appName: Test App
param: \&main::dynParam
someSection:
  valueA: AAAA
  valueB: \&main::valueB
anotherSection:
  value: BBB
request:
  hooks:
    before: \&main::sub_hooks
    after: \&main::sub_hooks
